<a href="https://colab.research.google.com/github/CharithManaujayaMUTEC/ChemGenAI/blob/main/ChemGenAI_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch pandas numpy matplotlib -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 530.6/530.6 MB 33.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.1/366.1 MB 26.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.9/169.9 MB 67.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.5/196.5 MB 65.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 MB 58.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.2/188.2 MB 66.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 MB 43.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 88.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 MB 62.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 88.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.1/214.1 MB 69.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 72.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [2]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn

In [3]:
df = pd.DataFrame({
    "smiles": [
        "CCO",
        "CCN",
        "CCC",
        "CC(=O)O",
        "C1=CC=CC=C1",
        "CCCl",
        "CCBr",
        "CCOC(=O)C",
        "CN",
        "CO"
    ]
})

df

,smiles
0,CCO
1,CCN
2,CCC
3,CC(=O)O
4,C1=CC=CC=C1
5,CCCl
6,CCBr
7,CCOC(=O)C
8,CN
9,CO


In [4]:
smiles_list = df["smiles"].tolist()

chars = sorted(list(set("".join(smiles_list))))

char_to_idx = {c:i+1 for i,c in enumerate(chars)}
idx_to_char = {i:c for c,i in char_to_idx.items()}

print(char_to_idx)

{'(': 1, ')': 2, '1': 3, '=': 4, 'B': 5, 'C': 6, 'N': 7, 'O': 8, 'l': 9, 'r': 10}


In [5]:
max_len = max(len(s) for s in smiles_list)

encoded = []

for s in smiles_list:
    seq = [char_to_idx[ch] for ch in s]
    seq += [0]*(max_len - len(seq))
    encoded.append(seq)

X = np.array(encoded)
print(X.shape)
print(X)

(10, 11)
[[ 6  6  8  0  0  0  0  0  0  0  0]
 [ 6  6  7  0  0  0  0  0  0  0  0]
 [ 6  6  6  0  0  0  0  0  0  0  0]
 [ 6  6  1  4  8  2  8  0  0  0  0]
 [ 6  3  4  6  6  4  6  6  4  6  3]
 [ 6  6  6  9  0  0  0  0  0  0  0]
 [ 6  6  5 10  0  0  0  0  0  0  0]
 [ 6  6  8  6  1  4  8  2  6  0  0]
 [ 6  7  0  0  0  0  0  0  0  0  0]
 [ 6  8  0  0  0  0  0  0  0  0  0]]


In [6]:
X_tensor = torch.tensor(X, dtype=torch.float32)